### ISSUE TITLE
Bluetooth error

### ISSUE THREAD

**Issue by tottoszsolt** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#3]
Hi,
I just installed it and besides bluetooth  eveything seems fine. Can you help me solve the bluetooth issue? I can see my phone and my phone can see my hackintosh, but after 1 sec of connection it just says not connected. Thank you for the answer!
Edit: 
The sleep mode works too only the bluetooth and the airdrop is the problem for me atleast... other than that excellent work! :D

**Comment by zamkara** [comment]
![image](https://user-images.githubusercontent.com/70899024/199853858-ae066e9c-4922-4863-a5c5-c1da95835dc3.png)
Hello, what is your Bluetooth device? I also use Bluetooth a lot but here it's safe even after hours, and also I never knew that Airdrop would work because previously it didn't work on my device, it seems our wireless devices are different.

**Comment by tottoszsolt** [comment]
I tried reinstalling it, I created the EFI and when I select the DMG to boot I just get a black screen so I cant reinstall it on my thinkpad.. can we contact maybe on dc or somewhere?
